version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: software.amazon.awssdk:ec2
    versions:
    - 2.15.72
    - 2.15.73
    - 2.15.74
    - 2.15.75
    - 2.15.76
    - 2.15.77
    - 2.15.78
    - 2.15.79
    - 2.15.80
    - 2.15.81
    - 2.15.82
    - 2.16.0
